version: '3.8'

services:
  open-telemorph-prime:
    build: .
    container_name: open-telemorph-prime
    ports:
      - "8080:8080"  # Web UI and REST API
      - "4317:4317"  # OTLP gRPC endpoint (traces, metrics, logs)
      - "4318:4318"  # OTLP HTTP endpoint (traces, metrics, logs)
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - CONFIG_PATH=/app/config.yaml
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  data:
